Repository Shemnei/punktf, pull requests merged in 2024-10, with the labels that each got.

#164 fix: Remove unused qualification and fix conditional compilation for wasm
  crates/punktf-lib/src/template/resolve.rs
  crates/punktf-lib/src/visit/mod.rs
Labels: bugfix

#166 fix(ci): Remove old actions-rs action
  .github/workflows/ci.yaml
Labels: enhancement

#165 chore: Update dependencies
  Cargo.lock
  Cargo.toml
  crates/punktf-cli/Cargo.toml
  crates/punktf-lib/Cargo.toml
  crates/punktf-lib/src/visit/deploy/mod.rs
  crates/punktf-lib/src/visit/mod.rs
Labels: dependencies

#167 fix: Handle binary template data properly
  Cargo.lock
  crates/punktf-lib/src/visit/deploy/mod.rs
  examples/80_simple_complete/dotfiles/wallpaper.png
  examples/80_simple_complete/profiles/simple.yml
Labels: bugfix

#169 chore(ci): Remove macos ci target
  .github/workflows/ci.yaml
Labels: github_actions
